### ISSUE TITLE
Templates not showing

### ISSUE THREAD

**Issue by Freeedooo** [didikunz/CasparCGAddIn#5]
Hey Didi,
I read your docu for the 100th time, but i cant select any templates in Excel. I think the server is connected correctly. Any recommendations?
The Server recieves my messages:
`[2022-02-03 16:16:11.691] [info]    Received message from 127.0.0.1: DATA STORE "Tabelle1" "<templateData><componentData id=\"_title\"><data id=\"text\" value=\"Fabian Buck\" /></componentData></templateData>"\r\n`
![image](https://user-images.githubusercontent.com/62063179/152370812-5d833f92-6d4b-4956-8744-366d2f597c33.png)

**Comment by didikunz** [comment]
Hey Freeedoo,

the command, that you see is the one, that is sent, when you hit Data-Sets Save. 

To be able to see templates listed you need to have Scanner.exe running, so that Caspar can query the templates (or run an old version like 2.0.7). To verify, you can key TLS <Enter> into Caspar's console window. If there is a listing with template names you should also be able to see them in the drop-down. Other ways post back here, before you start reading the manual for the second 100 times :)

**Comment by Freeedooo** [comment]
Thanks, Didi! Awesome AddIn. We´ll gonna use it for live eSports Production 👍
