### ISSUE TITLE
Increase update speed for timers

### ISSUE THREAD

**Issue by Freeedooo** [didikunz/CasparCGAddIn#7]
Is it possible to increase the update speed for the timers to catch up with the tenths? At the moment with the "one second update" it's just a standing zero, which looks a bit odd in my opinion.

**Comment by didikunz** [comment]
In theory it would be possible. Problem is, that it would need to update the display 10 times a second and that is a big burden to the system. I also do not see much use for it, as the timers are meant to be used on "slower" sports like football or running, where the accuracy of seconds is good enough. The display of 10th has more of a cosmetic nature. To start and stop a timer accurately by hand, so that the 10th of a second has a valid meaning, is very hard or impossible. Even in alpine skiing the TV 10th of a second display is fake and done without accurate data. You could do this inside of the template, and only display the "accurate" time, when the clock has been stopped. But as said, the start and stop would need to be triggered by some external device, like a photocell etc. to give exact results. For that the internal timer is not meant. One would need to build a custom solution.

**Comment by Freeedooo** [comment]
I did expect that. Thanks for your reply. love your work :)
